name: build
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-fr
          environment-file: environment.yml

      - name: Documents build
        run: ./build.py

      - name: Deployment Setup
        run: find . -name .gitignore -exec rm -rf {} \;

      - name: Observer
        run: find . -name .gitignore

      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true
